services:
#    viii_bit.example:
#        class: VIIIBitBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    viibit:
      class: VIIIBitBundle\Service\VIIbitService
      arguments: ["@service_container", "%viibit%"]